# -*- coding: utf-8 -*-
from setuptools import setup, find_packages

setup(
    name='strucgap',
    version='1.0.0',
    description='Structural and site-specific Glycoproteomics Analysis Platform',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    author='Muyao Yang',
    author_email='Muyao_Yang@proton.me',
    url='https://github.com/your-username/StrucGAP',
    packages=find_packages(),
    install_requires=[
        'pandas',
        'numpy',
        'scipy',
        'scikit-learn',
        'xgboost',
        'tqdm',
        'gprofiler',
        'umap',
        'matplotlib', 
        'PIL',
        'PyComplexHeatmap',
        'ast',
        'cairosvg',
        'copy',
        'datetime',
        'difflib',
        'fitz',
        'functools',
        'gseapy',
        'itertools',
        'math',
        'networkx',
        'operator',
        'os',
        'palettable',
        'pickle',
        'plotly',
        'pyecharts',
        'pyecharts_snapshot',
        'random',
        're',
        'reportlab',
        'requests',
        'seaborn',
        'snapshot_phantomjs',
        'statistics',
        'svglib',
        'types',
        'typing',
        'upsetplot',
        'venn',
        'werkzeug',

    ],
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
    ],
    python_requires='>=3.7',
)
